### ISSUE TITLE
Data Type Metadata with QID

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#194] opened 2024-09-02 19:46 UTC
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

[data_type_metadata](https://github.com/scribe-org/Scribe-Data/blob/9e9ceac3158deea011752c02f9fef4e01705b7c1/src/scribe_data/resources/data_type_metadata.json#L1)  should bear qid. [data-types](https://github.com/scribe-org/Scribe-Data/blob/9e9ceac3158deea011752c02f9fef4e01705b7c1/src/scribe_data/cli/total.py#L29) seams to be redundant.

**Comment by andrewtavis** [comment] 2024-09-02 20:32
If you'd like to send along a change for this, @axif0, then that would be fine, but the issue is that we decided that we're not going to do QIDs for data types as some languages are using different ones. But for now it's fine if you want to include the QIDs in the [data_type_metadata](https://github.com/scribe-org/Scribe-Data/blob/9e9ceac3158deea011752c02f9fef4e01705b7c1/src/scribe_data/resources/data_type_metadata.json#L1) part and then load that in and use it instead of [data_type_to_qid](https://github.com/scribe-org/Scribe-Data/blob/9e9ceac3158deea011752c02f9fef4e01705b7c1/src/scribe_data/cli/total.py#L29) :)

**Comment by andrewtavis** [comment] 2024-09-20 21:41
Closed by #199 😊 Thanks for diagnosing the issue and solving it so quickly, @axif0!

**Closed by andrewtavis** 2024-09-20 21:41 UTC
